<?php
declare(strict_types=1);

namespace Plaisio\LanguageResolver\Test\Plaisio;

use Plaisio\Babel\Babel;
use Plaisio\Babel\CoreBabel;
use Plaisio\LanguageResolver\CoreLanguageResolver;
use Plaisio\LanguageResolver\LanguageResolver;
use Plaisio\PlaisioKernel;
use Plaisio\Request\CoreRequest;
use Plaisio\Request\Request;

/**
 * Mock framework for testing purposes.
 */
class TestKernel extends PlaisioKernel
{
  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Returns the helper object for retrieving linguistic entities.
   *
   * @return Babel
   */
  protected function getBabel(): Babel
  {
    return new CoreBabel($this);
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Returns the data layer generated by PhpStratum.
   *
   * @return Object
   */
  protected function getDL(): object
  {
    return new TestDataLayer();
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * @return LanguageResolver
   */
  protected function getLanguageResolver(): LanguageResolver
  {
    return new CoreLanguageResolver($this, C::LAN_ID_EN);
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * @return Request
   */
  protected function getRequest(): Request
  {
    return new CoreRequest();
  }

  //--------------------------------------------------------------------------------------------------------------------
}

//----------------------------------------------------------------------------------------------------------------------
